# -*- coding: utf-8 -*-
"""
/***************************************************************************
 plugin12_14
                                 A QGIS plugin
 wtyczka dla grupy 
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2024-06-03
        copyright            : (C) 2024 by Krzysztof Łoza, Małgorzata Chodowiec, Miłosz Średnicki
        email                : krzysztof.loza03@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load plugin12_14 class from file plugin12_14.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .plugin12_14 import plugin12_14
    return plugin12_14(iface)
