# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'plugin12_14_dialog_base.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_plugin12_14DialogBase(object):
    def setupUi(self, plugin12_14DialogBase):
        plugin12_14DialogBase.setObjectName("plugin12_14DialogBase")
        plugin12_14DialogBase.resize(574, 413)
        self.button_box = QtWidgets.QDialogButtonBox(plugin12_14DialogBase)
        self.button_box.setGeometry(QtCore.QRect(200, 350, 341, 32))
        self.button_box.setOrientation(QtCore.Qt.Horizontal)
        self.button_box.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.button_box.setObjectName("button_box")
        self.label = QtWidgets.QLabel(plugin12_14DialogBase)
        self.label.setGeometry(QtCore.QRect(54, 35, 131, 51))
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(plugin12_14DialogBase)
        self.pushButton.setGeometry(QtCore.QRect(50, 90, 171, 51))
        self.pushButton.setObjectName("pushButton")
        self.label_2 = QtWidgets.QLabel(plugin12_14DialogBase)
        self.label_2.setGeometry(QtCore.QRect(340, 100, 161, 31))
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.mMapLayerComboBox = QgsMapLayerComboBox(plugin12_14DialogBase)
        self.mMapLayerComboBox.setGeometry(QtCore.QRect(320, 50, 221, 21))
        self.mMapLayerComboBox.setObjectName("mMapLayerComboBox")

        self.retranslateUi(plugin12_14DialogBase)
        self.button_box.accepted.connect(plugin12_14DialogBase.accept) # type: ignore
        self.button_box.rejected.connect(plugin12_14DialogBase.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(plugin12_14DialogBase)

    def retranslateUi(self, plugin12_14DialogBase):
        _translate = QtCore.QCoreApplication.translate
        plugin12_14DialogBase.setWindowTitle(_translate("plugin12_14DialogBase", "plugin 12-14"))
        self.label.setText(_translate("plugin12_14DialogBase", "Select layer"))
        self.pushButton.setText(_translate("plugin12_14DialogBase", "Calculate height difference"))
from qgsmaplayercombobox import QgsMapLayerComboBox


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    plugin12_14DialogBase = QtWidgets.QDialog()
    ui = Ui_plugin12_14DialogBase()
    ui.setupUi(plugin12_14DialogBase)
    plugin12_14DialogBase.show()
    sys.exit(app.exec_())
